<?php

namespace ContainerMtXTdt5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHaieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xtyMFIP.App\Entity\Haie' shared service.
     *
     * @return \App\Entity\Haie
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.xtyMFIP": it references class "App\\Entity\\Haie" but no such service exists.');
    }
}
