<?php

namespace ContainerFgxizBC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDevisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2zHYbv0.App\Entity\Devis' shared service.
     *
     * @return \App\Entity\Devis
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.2zHYbv0": it references class "App\\Entity\\Devis" but no such service exists.');
    }
}
